name: Build and Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 12 * * *"

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 21
        uses: actions/setup-node@v2
        with:
          node-version: 21
          cache: "npm"
      - run: npm install
      - run: npm run coverage
